[package]
name = "deployer"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
env_logger = "0.9.0"
hex-literal = "0.3.4"
tokio = "1.15.0"
web3 = "0.17.0"
