# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ""
        heroku_email: "benjcape@gmail.com"
        justlogin: true
    - run: make deploy
      env:
        SENDGRID_KEY: ${{ secrets.SENDGRID_KEY }}
  appsJson:
    runs-on: ubuntu-latest
    steps:
      - uses: juliangruber/read-file-action@v1
        with: 
          path: ../../../config.json
  deploy-apps:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app-name: ${{ fromJson(needs.appsJson.outputs).apps }}
    needs: [deploy, appsJson]
    steps:
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: "${{ matrix.app-name.name }}"
        heroku_email: "benjcape@gmail.com" 