# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Node.js CI

on:
  push:
    branches: [ dev ]
    paths-ignore:
      - "README.md"
      - ".gitignore"
      - ".github/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: make test
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
      with:
        heroku_api_key: ${{ secrets.DEV_HEROKU_API_KEY }}
        heroku_app_name: ""
        heroku_email: "benjamin.j.cape.22@dartmouth.com"
        justlogin: true
    - run: make deploy
      env:
        SENDGRID_KEY: ${{ secrets.SENDGRID_KEY }}
        STAGE: dev
  appsJson:
    runs-on: ubuntu-latest
    outputs:
      config: ${{ steps.js.outputs.content }}
    steps:
      - uses: actions/checkout@v2
      - name: Step 1
        id: js
        uses: juliangruber/read-file-action@v1 
        with: 
          path: config.json
  deploy-apps:
    runs-on: ubuntu-latest
    needs: [deploy, appsJson]
    strategy:
      max-parallel: 1
      matrix:
        app-name: ${{ fromJSON(needs.appsJson.outputs.config).dev }}
    steps:
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
      with:
        heroku_api_key: ${{ secrets.DEV_HEROKU_API_KEY }}
        heroku_app_name: "${{ matrix.app-name.name }}"
        heroku_email: "benjamin.j.cape.22@dartmouth.com" 